### ISSUE TITLE
データベースの内容までリポジトリにおく必要はないのでは

### ISSUE THREAD

**Issue by m4kvn** [taross/WordPressWithDocker#2]
このリポジトリをクローンして `docker-compose up -d` をし、
`localhost:8080` にアクセスしたが、WordPress が初期状態ではなく、
記事も投稿された状態だった。

このまま GitHub で管理するとデータベースのデータが多くなるにつれて、
GitHub におくデータが大きくなってしまう。

なので、データベースのデータを保存している部分のみ `.gitignore` で除外し、
初めて起動した際には、必ず初期状態の WordPress を起動する状態にするのが望ましい。

**Comment by m4kvn** [comment]
データベースのデータはローカルにのみ保存するようにします。

実際にサーバー上で運用した場合には、
サーバー上のデータベースを操作しバックアップを作成し、
それをローカルに落としてデータベースにインポートして使います。

なので、最新のデータは常にサーバー常にあります。

ローカルの環境でサーバーのデータベースに直接アクセスすることは可能ですが、
リスクを考えると推奨されません。

**Comment by taross** [comment]
了解しました！確かにそうですね。
データ自体は将来的に運用する（よてい）サーバーのみで保持することになりますから、今のうちに切り離しておいた方がいいですね。
